export const ui = {
  brand: "AERIS",
  tagline: "Secure Private Access",
  kyc: "KYC & IDENTITY ENTRY",
  documentTitle: "AERIS / The Trusted Real Estate Ledger",
  footer: {
    copyright: "© 2024 AERIS PRECISION REAL ESTATE. ALL RIGHTS RESERVED.",
    links: [
      { label: "Terms of sale", href: "#" },
      { label: "Privacy protocol", href: "#" },
      { label: "Regulatory disclosure", href: "#" },
    ],
  },
  landing: {
    searchPlaceholder: "Search properties...",
    viewMore: "View more",
    signIn: "Sign in",
    heroTitle: "Real Estate Transactions, Refined by Law.",
    heroBody:
      "Aeris provides a strictly verified, cryptographically secure environment for high-net-worth property exchange. Bypassing traditional brokerage layers entirely.",
    sell: "Sell direct",
    buy: "Buy verified",
    calculator: {
      title: "Brokerage Calculator",
      valueLabel: "Property Value",
      defaultValue: 5_000_000,
      traditionalLabel: "Traditional Fee (6%)",
      traditionalRate: 0.06,
      aerisLabel: "Aeris Flat Rate",
      aerisFlat: 15_000,
      retainedLabel: "Capital Retained",
    },
    passport: {
      title: "Property Passport",
      badge: "Live preview",
      id: "ID: P-882-NY",
      status: "Verified asset",
      rows: [
        { label: "Title Status", value: "CLEAR" },
        { label: "Environmental Audit", value: "PASSED '24" },
        { label: "Zoning Classification", value: "R-1 HIGH-DENSITY" },
      ],
      sync: "Blockchain ledger sync complete",
    },
    alpha: {
      title: "Verification Alpha.",
      body: "Every listing is subjected to a proprietary 124-point legal, structural, and financial stress test before it is admitted to the ledger.",
      points: [
        "Algorithmic Title Scrubbing",
        "Automated Escrow via Smart Contract",
        "Direct-to-Seller Communication Protocol",
      ],
    },
  },
  discover: {
    title: "Property Discovery",
    locationLabel: "Location or ID",
    locationPlaceholder: "Central Business District",
    budgetLabel: "Max Budget",
    budgetPlaceholder: "15,000,000",
    configLabel: "Configuration",
    configAll: "All types",
    configs: ["Commercial Tower", "Warehouse", "Retail", "Office Park", "Mixed Use"],
    filter: "Filter",
    verifiedOnly: "Only Show Legally Verified",
    viewDetails: "View details",
    analyze: "Analyze",
    area: "Area",
    status: "Status",
    price: "Price",
    yieldLabel: "Est. Yield",
    analytics: "Market Analytics",
    quarter: "Q3 2026",
    avgCap: "Avg Cap Rate",
    vacancy: "Vacancy Rate",
    yoy: "YoY Growth",
    empty: "No properties match these filters.",
    loading: "Loading listings…",
    prev: "Previous",
    next: "Next",
    close: "Close",
    pagination: "Listings pages",
    didYouMean: "Did you mean",
  },
  property: {
    idLabel: "Property ID",
    loading: "Loading property…",
    missing: "This listing is not on the ledger.",
    back: "Back to discovery",
    backProfile: "Back to profile",
    nav: [
      { id: "overview", label: "Overview" },
      { id: "contracts", label: "Contracts" },
      { id: "financials", label: "Financials" },
      { id: "timeline", label: "Timeline" },
      { id: "support", label: "Support" },
    ],
    message: "Secure message",
    desk: "Interest & chats",
    certified: "Verified",
    pendingReview: "Unverified",
    awaitingLawyer: "Pending",
    subscribeVerify: "Subscribe to verify",
    editListing: "Edit",
    deleteListing: "Delete",
    deleteTitle: "Delete this listing?",
    deleteConfirm: "This cannot be undone.",
    cancelEdit: "Cancel",
    saveListing: "Save listing",
    carpet: "Carpet Area",
    floor: "Floor Level",
    exposure: "Exposure",
    auditTitle: "Audit Checklist",
    auditBody: "Comprehensive legal and structural verification.",
    auditPass: "Verified",
    auditPending: "Pending",
    auditFail: "Unverified",
    audit: [
      { id: "title", label: "Title & Ownership" },
      { id: "tax", label: "Encumbrance & Tax" },
      { id: "rera", label: "Approvals & RERA" },
      { id: "lawyer", label: "Lawyer Sign-off" },
    ],
    ledgerTitle: "Blockchain Immutable Record",
    ledgerBody:
      "This passport is cryptographically hashed and anchored to a distributed ledger. Tampering is detectable on every subsequent read.",
    viewLedger: "View hash ledger",
    vaultTitle: "Property Vault",
    vaultBody: "A secure repository for this asset’s original instruments — cryptographically sealed and verified.",
    deedTitle: "Registered Sale Deed",
    verifiedSeal: "Verified Seal",
    encrypted: "AES-256 Encrypted",
    viewDoc: "View document",
    downloadPdf: "Download PDF",
    taxTitle: "Tax Tracker",
    nextAssessment: "Next Assessment",
    assessmentValue: "Q4 2026",
    estimatedDue: "Estimated Due",
    renewal: "Renewal due in {n} days.",
    schedule: "Schedule payment",
    concierge: "Concierge Services",
    services: [
      {
        id: "move",
        title: "Relocation Logistics",
        badge: "Recommended",
        body: "White-glove transfer of chattels, staff, and occupancy handover on a sealed schedule.",
        action: "Explore service",
      },
      {
        id: "interior",
        title: "Interior Commission",
        badge: "",
        body: "Appointed architectural designers for a fit-out that matches the passport specification.",
        action: "View portfolio",
      },
      {
        id: "protect",
        title: "Asset Protection",
        badge: "Active",
        body: "Title-linked cover for structure, contents, and loss of rent on this ledger entry.",
        action: "Manage policy",
      },
    ],
    financialsTitle: "Financials",
    financialsBody: "Yield, carrying cost, and the Aeris settlement fee on this listing.",
    price: "Price",
    yieldLabel: "Est. Yield",
    annualNet: "Est. Annual Net",
    yoy: "YoY Growth",
    aerisFee: "Aeris flat fee",
    carrying: "Est. annual tax",
    timelineTitle: "Timeline",
    timelineBody: "Legal and structural checkpoints recorded against this asset.",
    supportTitle: "Support",
    supportBody: "Counsel hours and answers for this listing. Sensitive items go through Secure message.",
    hours: "Counsel desk · Mon–Sat 10:00–18:00 IST",
    faqs: [
      {
        q: "Who holds the original deed?",
        a: "The registered instrument is vaulted under AES-256. Counsel can release a watermarked copy after identity check.",
      },
      {
        q: "How is the yield figure calculated?",
        a: "Net operating income over asking price, using the last four quarters of collected rent on the passport.",
      },
      {
        q: "Can I visit the site?",
        a: "Yes. Send a secure message with preferred slots. Access is logged against your KYC session.",
      },
    ],
    messageTitle: "Secure Message",
    messageBody: "A private channel with the listing owner. Messages stay on this passport.",
    deskTitle: "Interest & negotiations",
    deskBody: "Buyers tracking this listing, and private chats for offers.",
    deskEmpty: "No one has tracked or messaged this listing yet.",
    threadEmpty: "No messages yet.",
    pickBuyer: "Select a buyer to open the thread.",
    trackingNow: "Tracking",
    inChat: "In chat",
    chatCount: "messages",
    subject: "Subject",
    bodyLabel: "Message",
    send: "Send message",
    sent: "Message delivered to the listing owner.",
    demoNote: "Document preview is sealed in this demo.",
    hashLabel: "Ledger hash",
  },
  profile: {
    title: "Profile",
    body: "Ledger identity",
    details: "Profile details",
    name: "Name",
    email: "Email",
    phone: "Mobile",
    save: "Save",
    saved: "Profile saved.",
    loading: "Loading profile…",
    listed: "Listed",
    listedHint: "Properties to sell",
    watching: "Watching",
    watchingHint: "On your list",
    insightLabel: "Discovery",
    insight: "Demand on verified listings is up this week.",
    selling: "Properties to sell",
    interested: "Properties I’m interested in",
    sellingEmpty: "You have not listed a property yet.",
    interestedEmpty: "Track a listing from discovery to follow it here.",
    remove: "Remove",
    track: "Track",
    tracking: "Tracking",
    addListing: "Add property",
    browse: "Browse listings",
    view: "View",
    logout: "Log out",
  },
  sell: {
    title: "Seller Dashboard",
    subtitle: "Q3 Performance Metrics",
    add: "+ Add new property",
    views: "Total Views",
    viewsDelta: "vs last month",
    offers: "Active Offers",
    offersHint: "Awaiting review",
    insight: "Market Insight",
    listings: "Active Properties",
    colProperty: "Property",
    colPrice: "List Price",
    colStatus: "Status",
    colActions: "Actions",
    view: "View",
    delete: "Delete",
    empty: "No listings yet. Add a property to open the ledger.",
    loading: "Loading listings…",
    live: "Verified",
    negotiation: "Negotiation",
    pending: "Pending",
    unverified: "Unverified",
    back: "Back to dashboard",
    goBack: "Go back",
    stepBasic: "Basic details",
    stepPhotos: "Photography & media",
    details: "Property Details",
    edit: "Edit",
    type: "Type",
    area: "Area (sqft)",
    price: "Price",
    titleField: "Title",
    locationField: "Location",
    nextPhotos: "Continue to photography",
    drop: "Drag and drop high-resolution imagery",
    dropHint: "JPEG, PNG, WEBP (max 50MB per file)",
    pin: "Adjust map pin",
    publish: "Continue to publish",
    publishing: "Publishing…",
  },
  verify: {
    title: "Select Your Verification Package",
    body: "Legal and financial scrutiny on this listing, sealed to the passport.",
    cancel: "Cancel",
    recommended: "Recommended",
    selected: "Selected",
    checkout: "Secure Checkout",
    checkoutBody: "Pay on Razorpay — UPI QR on desktop, UPI apps on phone, plus card, netbanking, and wallet.",
    packLabel: "Package",
    fee: "Processing Fee (2.9%)",
    total: "Total",
    ssl: "256-bit SSL Encrypted",
    pay: "Pay with Razorpay",
    paying: "Opening Razorpay…",
    packs: {
      basic: {
        name: "Basic",
        select: "Select Basic",
        features: ["Initial KYC / AML", "Standard document review", "Digital certificate of authenticity"],
      },
      verified: {
        name: "Verified",
        select: "Select Verified",
        features: [
          "Deep-dive corporate audit",
          "Beneficial ownership verification",
          "Jurisdictional risk assessment",
          "Notarized legal opinion",
        ],
      },
      escrow: {
        name: "Escrow-Ready",
        select: "Select Escrow-Ready",
        features: ["Full Verified package", "Escrow account setup", "Smart contract integration", "Dedicated concierge"],
      },
    },
  },
  notifications: {
    label: "Notifications",
    empty: "No notifications yet.",
    markAll: "Mark all read",
    signIn: "Sign in to see notifications.",
  },
} as const;
